# Generated by Django 3.2.3 on 2021-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.GenericIPAddressField(db_index=True)),
                ('dst', models.GenericIPAddressField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_size', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.GenericIPAddressField(db_index=True)),
                ('dst', models.GenericIPAddressField(db_index=True)),
                ('time', models.DateTimeField()),
                ('size', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=64)),
                ('app', models.CharField(max_length=256)),
            ],
        ),
    ]
